# Generated by Django 2.2.1 on 2019-11-18 15:05

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserDetails',
        ),
    ]
