# Generated by Django 2.2.1 on 2019-11-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20191118_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='username',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
